![data-x](http://oi64.tinypic.com/o858n4.jpg)

___

# Homework 03


## Name: Miran Tafazzul Hussain Junaidi

## Student ID: 3034487132

## Note: Please print the output of each question in a new cell below your code



## Numpy Introduction


__1a) Create two numpy arrays (a and b). a should be all integers between 25-34 (inclusive), and b should be ten evenly spaced numbers between 1-6. Print all the results below and store them seperately:__


i) Cube (i.e. raise to the power of 3) all the elements in both arrays (element-wise)  
ii)  Add both the cubed arrays (e.g., [1,2] + [3,4] = [4,6])  
iii)  Sum the elements with even indices of the added array.  
iv)  Take the square root of the added array (element-wise square root)




In [1]:
# your code here
#creating the array a
import numpy as np
a = np.array([x for x in range(25,35)])
a

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [2]:
#Creating the array b
b_list= [1]
for i in range (9):
    b_list.append(b_list[i]+ 5/10)
b = np.array(b_list)
b

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [3]:
#Cubing both the arrays
a_cubed = a**3
b_cubed = b**3
print(a_cubed)
print(b_cubed)

[15625 17576 19683 21952 24389 27000 29791 32768 35937 39304]
[  1.      3.375   8.     15.625  27.     42.875  64.     91.125 125.
 166.375]


In [4]:
cubed_sum = np.add(a_cubed,b_cubed)
cubed_sum

array([15626.   , 17579.375, 19691.   , 21967.625, 24416.   , 27042.875,
       29855.   , 32859.125, 36062.   , 39470.375])

In [5]:
#Sum of the elements with even indices of the cubed and added arrays
even_index_sum=0

for i in cubed_sum[::2] :
    even_index_sum += i
even_index_sum

125650.0

In [6]:
# Square root of cubed_sum
cbd_sum_sqrt = cubed_sum **0.5
cbd_sum_sqrt

array([125.00399994, 132.58723543, 140.32462364, 148.21479346,
       156.25619988, 164.44717997, 172.7859948 , 181.27086087,
       189.89997367, 198.67152539])

__1b) Append b to a, reshape the appended array so that it is a 4x5, 2d array and store the results in a variable called m. Print m.__


In [7]:
# your code here
m = np.concatenate([a,b], axis = 0)
m = m.reshape(4,5)
m   

array([[25. , 26. , 27. , 28. , 29. ],
       [30. , 31. , 32. , 33. , 34. ],
       [ 1. ,  1.5,  2. ,  2.5,  3. ],
       [ 3.5,  4. ,  4.5,  5. ,  5.5]])

__1c) Extract the third and the fourth column of the m matrix. Store the resulting 4x2 matrix in a new variable called m2. Print m2.__


In [8]:
# your code here
m2 = m[:,2:4]
m2

array([[27. , 28. ],
       [32. , 33. ],
       [ 2. ,  2.5],
       [ 4.5,  5. ]])

__1d) Take the dot product of m2 and m store the results in a matrix called m3. Print m3.
Note that Dot product of two matrices A.B =A<sup>T</sup>B__

In [9]:
# your code here
m2_t = m2.transpose()
m3 = m2_t.dot(m)
m3

array([[1652.75, 1715.  , 1777.25, 1839.5 , 1901.75],
       [1710.  , 1774.75, 1839.5 , 1904.25, 1969.  ]])

## Numpy conditions


__2a) Create a numpy array called 'f' where the values are cosine(x) for x from 0 to pi with 50 equally spaced values in f__
* Print f
* Use condition on the array and print an array that is True when f >= 1/2 and False when f < 1/2
* Create and print an array sequence that has only those values where f>= 1/2



In [10]:
# your code here
import math
f_noncos = np.linspace(0,np.pi,50)
f = np.cos(f_noncos)
f

array([ 1.        ,  0.99794539,  0.99179001,  0.98155916,  0.96729486,
        0.94905575,  0.92691676,  0.90096887,  0.8713187 ,  0.8380881 ,
        0.80141362,  0.76144596,  0.71834935,  0.67230089,  0.6234898 ,
        0.57211666,  0.51839257,  0.46253829,  0.40478334,  0.34536505,
        0.28452759,  0.22252093,  0.1595999 ,  0.09602303,  0.03205158,
       -0.03205158, -0.09602303, -0.1595999 , -0.22252093, -0.28452759,
       -0.34536505, -0.40478334, -0.46253829, -0.51839257, -0.57211666,
       -0.6234898 , -0.67230089, -0.71834935, -0.76144596, -0.80141362,
       -0.8380881 , -0.8713187 , -0.90096887, -0.92691676, -0.94905575,
       -0.96729486, -0.98155916, -0.99179001, -0.99794539, -1.        ])

In [11]:
#Boolian array
f_bool = f>=0.5
f_bool

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [12]:
#f with elelments grater than  or equal to 1/2
f[f_bool]

array([1.        , 0.99794539, 0.99179001, 0.98155916, 0.96729486,
       0.94905575, 0.92691676, 0.90096887, 0.8713187 , 0.8380881 ,
       0.80141362, 0.76144596, 0.71834935, 0.67230089, 0.6234898 ,
       0.57211666, 0.51839257])

## NumPy and 2 Variable Prediction

__Let 'x' be the number of miles a person drives per day and 'y' be the dollars spent on buying car fuel (per day).__
  
__We have created 2 numpy arrays each of size 100 that represent x and y.  
x ( number of miles) ranges from 1 to 10 with a uniform noise of (0,1/2)  
y (money spent in dollars) will be from 1 to 20 with a uniform noise (0,1)__ 


In [13]:
# seed the random number generator with a fixed value
import numpy as np
np.random.seed(500)

x = np.linspace(1,10,100)+ np.random.uniform(low=0,high=.5,size=100) 
y = np.linspace(1,20,100)+ np.random.uniform(low=0,high=1,size=100)
print('x = ',x)
print('y = ',y)

x =  [ 1.34683976  1.12176759  1.51512398  1.55233174  1.40619168  1.65075498
  1.79399331  1.80243817  1.89844195  2.00100023  2.3344038   2.22424872
  2.24914511  2.36268477  2.49808849  2.8212704   2.68452475  2.68229427
  3.09511169  2.95703884  3.09047742  3.2544361   3.41541904  3.40886375
  3.50672677  3.74960644  3.64861355  3.7721462   3.56368566  4.01092701
  4.15630694  4.06088549  4.02517179  4.25169402  4.15897504  4.26835333
  4.32520644  4.48563164  4.78490721  4.84614839  4.96698768  5.18754259
  5.29582013  5.32097781  5.0674106   5.47601124  5.46852704  5.64537452
  5.49642807  5.89755027  5.68548923  5.76276141  5.94613234  6.18135713
  5.96522091  6.0275473   6.54290191  6.4991329   6.74003765  6.81809807
  6.50611821  6.91538752  7.01250925  6.89905417  7.31314433  7.20472297
  7.1043621   7.48199528  7.58957227  7.61744354  7.6991707   7.85436822
  8.03510784  7.80787781  8.22410224  7.99366248  8.40581097  8.28913792
  8.45971515  8.54227144  8.6906456   8.618565

__3a) Find Expected value of x and the expected value of y__

In [14]:
# your code here
e_x = np.mean(x)
e_y = np.mean(y)
print("Expected Value of X = " , e_x)
print("Expected Value of Y = " , e_y)

Expected Value of X =  5.782532541587923
Expected Value of Y =  11.012981683344968


__3b) Find variance of distributions of  x and  y__

In [15]:
# your code here
print("Variance of X = ", np.var(x))
print("Variance of Y = ", np.var(y))

Variance of X =  7.03332752947585
Variance of Y =  30.113903575509635


__3c) Find co-variance of x and y.__

In [16]:
# your code here
xy= x*y
e_xy = np.mean(xy)
covar = e_xy - e_x * e_y
covar

14.511166394475424

__3d) Assuming that number of dollars spent in car fuel is only dependant on the miles driven, by  a linear relationship.  
Write code that uses a linear predictor to calculate a predicted value of y for each x
i.e y_predicted = f(x) = y0+mx. (Do not use Machine learning libraries)__ 

In [17]:
# your code here
m = covar / np.var(x)
c = e_y - m*e_x
m
x_in = int(input("Enter the miles driven"))
def pred_cost(miles,m,c):
    y_ou = m*x_in + c
    return y_ou
print("The amount spent on feul is $", pred_cost(x_in, m, c))

Enter the miles driven10
The amount spent on feul is $ 19.71446356312654


__3e) Predict y for each value in x, put the error into an array called y_error__

In [18]:
# your code here
y_p = m*x + c
y_error = y_p - y
y_error


array([ 0.19775597, -0.62457111,  0.10030076,  0.02506341,  0.02083649,
       -0.46716823, -0.24499418, -0.53440482,  0.24466541, -0.21408918,
        0.50209852,  0.27775029, -0.06213923, -0.42578118, -0.0931215 ,
        0.86405311, -0.1157489 ,  0.31558388,  0.62666017,  0.40166149,
        0.46107377,  0.47954311,  0.3607047 ,  0.17838904,  0.58942116,
        0.10891094, -0.07115518,  0.29032384, -0.74232081, -0.19082863,
        0.35553767,  0.14062095, -0.39304511, -0.0567791 , -0.61328502,
       -0.80310676, -0.77597321, -0.12176065,  0.06373323,  0.26383402,
        0.45927925,  0.12347238,  0.60673379,  0.20079382, -0.0660562 ,
        0.30670405, -0.33067419,  0.062778  , -0.75987212,  0.67596798,
       -0.65468531,  0.02820071,  0.08606832, -0.26171143, -0.72997592,
       -0.60306068,  0.40563939,  0.05397013, -0.02061681,  0.28548928,
       -0.7405245 ,  0.58908804,  0.43343988, -0.76182107, -0.02727604,
       -0.32564401, -0.56606805, -0.11129392,  0.46417555, -0.27

__3f) Write code that calculates the root mean square error(RMSE), that is root of average of y-error squared__


In [19]:
#your code here
RMS_Error = np.sqrt((y_error**2).mean())
RMS_Error


0.41767772366856115

## Pandas Introduction


##  Reading File


In [20]:
# Load required modules
import pandas as pd
import numpy as np



#### Read the CSV file called 'data3.csv' into a dataframe called df. 
#### Data description
* File location: https://bcourses.berkeley.edu/files/74463396/download?download_frd=1
* Data source: http://www.fao.org/nr/water/aquastat/data/query/index.html?*lang=en
* Data, units:
* GDP, current USD (CPI adjusted)
* NRI, mm/yr
* Population density, inhab/km^2
* Total area of the country, 1000 ha = 10km^2
* Total Population, unit 1000 inhabitants


In [21]:
# your code here
data = pd.read_csv("data3.csv")
data


Area  Area Id  \
0                                            Argentina      9.0   
1                                            Argentina      9.0   
2                                            Argentina      9.0   
3                                            Argentina      9.0   
4                                            Argentina      9.0   
5                                            Argentina      9.0   
6                                            Argentina      9.0   
7                                            Argentina      9.0   
8                                            Argentina      9.0   
9                                            Argentina      9.0   
10                                           Argentina      9.0   
11                                           Argentina      9.0   
12                                           Argentina      9.0   
13                                           Argentina      9.0   
14                                           Argentina      9.0   
15                                           Argentina      9.0   
16                                           Argentina      9.0   
17                                           Argentina      9.0   
18                                           Argentina      9.0   
19                                           Argentina      9.0   
20                                           Argentina      9.0   
21                                           Argentina      9.0   
22                                           Argentina      9.0   
23                                           Argentina      9.0   
24                                           Argentina      9.0   
25                                           Argentina      9.0   
26                                           Argentina      9.0   
27                                           Argentina      9.0   
28                                           Argentina      9.0   
29                                           Argentina      9.0   
..                                                 ...      ...   
368                           United States of America    231.0   
369                           United States of America    231.0   
370                           United States of America    231.0   
371                           United States of America    231.0   
372                           United States of America    231.0   
373                           United States of America    231.0   
374                           United States of America    231.0   
375                           United States of America    231.0   
376                           United States of America    231.0   
377                           United States of America    231.0   
378                           United States of America    231.0   
379                           United States of America    231.0   
380                           United States of America    231.0   
381                           United States of America    231.0   
382                           United States of America    231.0   
383                           United States of America    231.0   
384                           United States of America    231.0   
385                           United States of America    231.0   
386                           United States of America    231.0   
387                           United States of America    231.0   
388                           United States of America    231.0   
389                           United States of America    231.0   
390                                                NaN      NaN   
391                                  E - External data      NaN   
392                              I - AQUASTAT estimate      NaN   
393                                 K - Aggregate data      NaN   
394                                  L - Modelled data      NaN   
395                                 (c)  FAO of the UN      NaN   
396  The information contained

#### 4a ) Display the first 10 rows of the dataframe

In [22]:
# your code here
data[0:10]

Area  Area Id              Variable Name  Variable Id    Year  \
0  Argentina      9.0  Total area of the country       4100.0  1962.0   
1  Argentina      9.0  Total area of the country       4100.0  1967.0   
2  Argentina      9.0  Total area of the country       4100.0  1972.0   
3  Argentina      9.0  Total area of the country       4100.0  1977.0   
4  Argentina      9.0  Total area of the country       4100.0  1982.0   
5  Argentina      9.0  Total area of the country       4100.0  1987.0   
6  Argentina      9.0  Total area of the country       4100.0  1992.0   
7  Argentina      9.0  Total area of the country       4100.0  1997.0   
8  Argentina      9.0  Total area of the country       4100.0  2002.0   
9  Argentina      9.0  Total area of the country       4100.0  2007.0   

      Value Symbol  Other  
0  278040.0      E    NaN  
1  278040.0      E    NaN  
2  278040.0      E    NaN  
3  278040.0      E    NaN  
4  278040.0      E    NaN  
5  278040.0      E    NaN  
6  278040.0      E    NaN  
7  278040.0      E    NaN  
8  278040.0      E    NaN  
9  278040.0      E    NaN

#### 4b) Display the column names.

In [23]:
# your code here
list(data)

['Area',
 'Area Id',
 'Variable Name',
 'Variable Id',
 'Year',
 'Value',
 'Symbol',
 'Other']

#### 4c) Use iloc to display the first 3 rows and first 4 columns.

In [24]:
# your code here
data.iloc[0:3,0:4]

Area  Area Id              Variable Name  Variable Id
0  Argentina      9.0  Total area of the country       4100.0
1  Argentina      9.0  Total area of the country       4100.0
2  Argentina      9.0  Total area of the country       4100.0



## Data Preprocessing

#### 5a ) Find all the rows that  have 'NaN' in the 'Symbol' column. Display first 5 rows.

##### Hint : You might have to use a condition (mask)

In [25]:
# your code here

No_sym_df = data[:][data['Symbol'] != 'E' ]
No_sym_df[0:5]

Area  Area Id Variable Name  Variable Id  Year  Value  \
390                    NaN      NaN           NaN          NaN   NaN    NaN   
391      E - External data      NaN           NaN          NaN   NaN    NaN   
392  I - AQUASTAT estimate      NaN           NaN          NaN   NaN    NaN   
393     K - Aggregate data      NaN           NaN          NaN   NaN    NaN   
394      L - Modelled data      NaN           NaN          NaN   NaN    NaN   

    Symbol  Other  
390    NaN    NaN  
391    NaN    NaN  
392    NaN    NaN  
393    NaN    NaN  
394    NaN    NaN

#### 5b )  Now, we will try to get rid of the NaN valued rows and columns. First, drop the column 'Other' which only has 'NaN' values. Then drop all other rows that have any column with a value 'NaN'.  Then display the last 5 rows of the dataframe.

In [26]:
# your code here
data_no_nan = data.drop("Other", axis = 1)
data_no_nan = data_no_nan.dropna()
data_no_nan

Area  Area Id                  Variable Name  \
0                   Argentina      9.0      Total area of the country   
1                   Argentina      9.0      Total area of the country   
2                   Argentina      9.0      Total area of the country   
3                   Argentina      9.0      Total area of the country   
4                   Argentina      9.0      Total area of the country   
5                   Argentina      9.0      Total area of the country   
6                   Argentina      9.0      Total area of the country   
7                   Argentina      9.0      Total area of the country   
8                   Argentina      9.0      Total area of the country   
9                   Argentina      9.0      Total area of the country   
10                  Argentina      9.0      Total area of the country   
11                  Argentina      9.0      Total area of the country   
12                  Argentina      9.0               Total population   
13                  Argentina      9.0               Total population   
14                  Argentina      9.0               Total population   
15                  Argentina      9.0               Total population   
16                  Argentina      9.0               Total population   
17                  Argentina      9.0               Total population   
18                  Argentina      9.0               Total population   
19                  Argentina      9.0               Total population   
20                  Argentina      9.0               Total population   
21                  Argentina      9.0               Total population   
22                  Argentina      9.0               Total population   
23                  Argentina      9.0               Total population   
24                  Argentina      9.0             Population density   
25                  Argentina      9.0             Population density   
26                  Argentina      9.0             Population density   
27                  Argentina      9.0             Population density   
28                  Argentina      9.0             Population density   
29                  Argentina      9.0             Population density   
..                        ...      ...                            ...   
360  United States of America    231.0             Population density   
361  United States of America    231.0             Population density   
362  United States of America    231.0             Population density   
363  United States of America    231.0             Population density   
364  United States of America    231.0             Population density   
365  United States of America    231.0             Population density   
366  United States of America    231.0             Population density   
367  United States of America    231.0             Population density   
368  United States of America    231.0             Population density   
369  United States of America    231.0             Population density   
370  United States of America    231.0   Gross Domestic Product (GDP)   
371  United States of America    231.0   Gross Domestic Product (GDP)   
372  United States of America    231.0   Gross Domestic Product (GDP)   
373  United States of America    231.0   Gross Domestic Product (GDP)   
374  United States of America    231.0   Gross Domestic Product (GDP)   
375  United States of America    231.0   Gross Domestic Product (GDP)   
376  United States of America    231.0   Gross Domestic Product (GDP)   
377  United States of America    231.0   Gross Domestic Product (GDP)   
378  United States of America    231.0   Gross Domestic Product (GDP)   
379  United States of America    231.0   Gross Domestic Product (GDP)   
380  United States of America    231.0   Gross Domestic Product (GDP)   
381  United States of America    231.0   Gross Domestic Product (GDP)   
382  United States of America    231.0  National Rainfall Index (NRI)   
383  Unite




#### 6a) For our analysis we do not want all the columns in our dataframe. Lets  drop all the redundant columns/ features.   
#### **Drop columns**: **Area Id, Variable Id, Symbol**. Save the new dataframe as df1. Display the first 5 rows of the new dataframe.


In [27]:
# your code here
data_no_nan = data_no_nan.drop('Area Id', axis = 1)
data_no_nan = data_no_nan.drop('Variable Id', axis = 1)
data_no_nan = data_no_nan.drop('Symbol', axis = 1)
df1 = data_no_nan
df1

Area                  Variable Name    Year  \
0                   Argentina      Total area of the country  1962.0   
1                   Argentina      Total area of the country  1967.0   
2                   Argentina      Total area of the country  1972.0   
3                   Argentina      Total area of the country  1977.0   
4                   Argentina      Total area of the country  1982.0   
5                   Argentina      Total area of the country  1987.0   
6                   Argentina      Total area of the country  1992.0   
7                   Argentina      Total area of the country  1997.0   
8                   Argentina      Total area of the country  2002.0   
9                   Argentina      Total area of the country  2007.0   
10                  Argentina      Total area of the country  2012.0   
11                  Argentina      Total area of the country  2014.0   
12                  Argentina               Total population  1962.0   
13                  Argentina               Total population  1967.0   
14                  Argentina               Total population  1972.0   
15                  Argentina               Total population  1977.0   
16                  Argentina               Total population  1982.0   
17                  Argentina               Total population  1987.0   
18                  Argentina               Total population  1992.0   
19                  Argentina               Total population  1997.0   
20                  Argentina               Total population  2002.0   
21                  Argentina               Total population  2007.0   
22                  Argentina               Total population  2012.0   
23                  Argentina               Total population  2015.0   
24                  Argentina             Population density  1962.0   
25                  Argentina             Population density  1967.0   
26                  Argentina             Population density  1972.0   
27                  Argentina             Population density  1977.0   
28                  Argentina             Population density  1982.0   
29                  Argentina             Population density  1987.0   
..                        ...                            ...     ...   
360  United States of America             Population density  1972.0   
361  United States of America             Population density  1977.0   
362  United States of America             Population density  1982.0   
363  United States of America             Population density  1987.0   
364  United States of America             Population density  1992.0   
365  United States of America             Population density  1997.0   
366  United States of America             Population density  2002.0   
367  United States of America             Population density  2007.0   
368  United States of America             Population density  2012.0   
369  United States of America             Population density  2015.0   
370  United States of America   Gross Domestic Product (GDP)  1962.0   
371  United States of America   Gross Domestic Product (GDP)  1967.0   
372  United States of America   Gross Domestic Product (GDP)  1972.0   
373  United States of America   Gross Domestic Product (GDP)  1977.0   
374  United States of America   Gross Domestic Product (GDP)  1982.0   
375  United States of America   Gross Domestic Product (GDP)  1987.0   
376  United States of America   Gross Domestic Product (GDP)  1992.0   
377  United States of America   Gross Domestic Product (GDP)  1997.0   
378  United States of America   Gross Domestic Product (GDP)  2002.0   
379  United States of America   Gross Domestic Product (GDP)  2007.0   
380  United States of America   Gross Domestic Product (GDP)  2012.0   
381  United States of America   Gross Domestic Product (GDP)  2015.0   
382  United States of America  National Rainfall Index (NRI)  1965.0   
383  United States of America  National Rainfall Index (NRI)  196

#### 6b) Display all the unique values in your new dataframe for columns: Area, Variable Name, Year.


In [28]:
# your code here
df1['Area'].unique()

array(['Argentina', 'Australia', 'Germany', 'Iceland', 'Ireland',
       'Sweden', 'United States of America'], dtype=object)

In [29]:
df1['Variable Name'].unique()

array(['Total area of the country', 'Total population',
       'Population density', 'Gross Domestic Product (GDP)',
       'National Rainfall Index (NRI)'], dtype=object)

In [30]:
df1['Year'].unique()

array([1962., 1967., 1972., 1977., 1982., 1987., 1992., 1997., 2002.,
       2007., 2012., 2014., 2015., 1963., 1970., 1974., 1978., 1984.,
       1990., 1964., 1981., 1985., 1996., 2001., 1969., 1973., 1979.,
       1993., 1971., 1975., 1986., 1991., 1998., 2000., 1965., 1983.,
       1988., 1995.])

__6c) Convert the year column to pandas datetime. Convert the 'Year' column float values to pandas datetime objects, where each year is represented as the first day of that year. Also display the column and datatype for 'Year' after conversion.
For eg: 1962.0 will be represented as 1962-01-01¶__


In [31]:
df1['Year'] = pd.to_datetime(df1['Year'], format = "%Y.0")
s1 = df1['Year']
print(type(s1[1]))
df1

<class 'pandas._libs.tslibs.timestamps.Timestamp'>


Area                  Variable Name       Year  \
0                   Argentina      Total area of the country 1962-01-01   
1                   Argentina      Total area of the country 1967-01-01   
2                   Argentina      Total area of the country 1972-01-01   
3                   Argentina      Total area of the country 1977-01-01   
4                   Argentina      Total area of the country 1982-01-01   
5                   Argentina      Total area of the country 1987-01-01   
6                   Argentina      Total area of the country 1992-01-01   
7                   Argentina      Total area of the country 1997-01-01   
8                   Argentina      Total area of the country 2002-01-01   
9                   Argentina      Total area of the country 2007-01-01   
10                  Argentina      Total area of the country 2012-01-01   
11                  Argentina      Total area of the country 2014-01-01   
12                  Argentina               Total population 1962-01-01   
13                  Argentina               Total population 1967-01-01   
14                  Argentina               Total population 1972-01-01   
15                  Argentina               Total population 1977-01-01   
16                  Argentina               Total population 1982-01-01   
17                  Argentina               Total population 1987-01-01   
18                  Argentina               Total population 1992-01-01   
19                  Argentina               Total population 1997-01-01   
20                  Argentina               Total population 2002-01-01   
21                  Argentina               Total population 2007-01-01   
22                  Argentina               Total population 2012-01-01   
23                  Argentina               Total population 2015-01-01   
24                  Argentina             Population density 1962-01-01   
25                  Argentina             Population density 1967-01-01   
26                  Argentina             Population density 1972-01-01   
27                  Argentina             Population density 1977-01-01   
28                  Argentina             Population density 1982-01-01   
29                  Argentina             Population density 1987-01-01   
..                        ...                            ...        ...   
360  United States of America             Population density 1972-01-01   
361  United States of America             Population density 1977-01-01   
362  United States of America             Population density 1982-01-01   
363  United States of America             Population density 1987-01-01   
364  United States of America             Population density 1992-01-01   
365  United States of America             Population density 1997-01-01   
366  United States of America             Population density 2002-01-01   
367  United States of America             Population density 2007-01-01   
368  United States of America             Population density 2012-01-01   
369  United States of America             Population density 2015-01-01   
370  United States of America   Gross Domestic Product (GDP) 1962-01-01   
371  United States of America   Gross Domestic Product (GDP) 1967-01-01   
372  United States of America   Gross Domestic Product (GDP) 1972-01-01   
373  United States of America   Gross Domestic Product (GDP) 1977-01-01   
374  United States of America   Gross Domestic Product (GDP) 1982-01-01   
375  United States of America   Gross Domestic Product (GDP) 1987-01-01   
376  United States of America   Gross Domestic Product (GDP) 1992-01-01   
377  United States of America   Gross Domestic Product (GDP) 1997-01-01   
378  United States of America   Gross Domestic Product (GDP) 2002-01-01   
379  United States of America   Gross Domestic Product (GDP) 2007-01-01   
380  United States of America   Gross Domestic Product (GDP) 2012-01-01   
381  United States of America   Gross Domestic Pro

## Extract specific statistics from the preprocessed data:

#### 7a)  Create a dataframe 'dftemp' to store rows where Area is 'Iceland'. Display the dataframe.

In [32]:
# your code here
dftemp = df1[:][df1['Area'] == 'Iceland']
dftemp

Area                  Variable Name       Year         Value
166  Iceland      Total area of the country 1962-01-01  1.030000e+04
167  Iceland      Total area of the country 1967-01-01  1.030000e+04
168  Iceland      Total area of the country 1972-01-01  1.030000e+04
169  Iceland      Total area of the country 1977-01-01  1.030000e+04
170  Iceland      Total area of the country 1982-01-01  1.030000e+04
171  Iceland      Total area of the country 1987-01-01  1.030000e+04
172  Iceland      Total area of the country 1992-01-01  1.030000e+04
173  Iceland      Total area of the country 1997-01-01  1.030000e+04
174  Iceland      Total area of the country 2002-01-01  1.030000e+04
175  Iceland      Total area of the country 2007-01-01  1.030000e+04
176  Iceland      Total area of the country 2012-01-01  1.030000e+04
177  Iceland      Total area of the country 2014-01-01  1.030000e+04
178  Iceland               Total population 1962-01-01  1.826000e+02
179  Iceland               Total population 1967-01-01  1.974000e+02
180  Iceland               Total population 1972-01-01  2.099000e+02
181  Iceland               Total population 1977-01-01  2.221000e+02
182  Iceland               Total population 1982-01-01  2.331000e+02
183  Iceland               Total population 1987-01-01  2.469000e+02
184  Iceland               Total population 1992-01-01  2.599000e+02
185  Iceland               Total population 1997-01-01  2.728000e+02
186  Iceland               Total population 2002-01-01  2.869000e+02
187  Iceland               Total population 2007-01-01  3.054000e+02
188  Iceland               Total population 2012-01-01  3.234000e+02
189  Iceland               Total population 2015-01-01  3.294000e+02
190  Iceland             Population density 1962-01-01  1.773000e+00
191  Iceland             Population density 1967-01-01  1.917000e+00
192  Iceland             Population density 1972-01-01  2.038000e+00
193  Iceland             Population density 1977-01-01  2.156000e+00
194  Iceland             Population density 1982-01-01  2.263000e+00
195  Iceland             Population density 1987-01-01  2.397000e+00
196  Iceland             Population density 1992-01-01  2.523000e+00
197  Iceland             Population density 1997-01-01  2.649000e+00
198  Iceland             Population density 2002-01-01  2.785000e+00
199  Iceland             Population density 2007-01-01  2.965000e+00
200  Iceland             Population density 2012-01-01  3.140000e+00
201  Iceland             Population density 2015-01-01  3.198000e+00
202  Iceland   Gross Domestic Product (GDP) 1962-01-01  2.849165e+08
203  Iceland   Gross Domestic Product (GDP) 1967-01-01  6.212260e+08
204  Iceland   Gross Domestic Product (GDP) 1972-01-01  8.465069e+08
205  Iceland   Gross Domestic Product (GDP) 1977-01-01  2.226539e+09
206  Iceland   Gross Domestic Product (GDP) 1982-01-01  3.232804e+09
207  Iceland   Gross Domestic Product (GDP) 1987-01-01  5.565384e+09
208  Iceland   Gross Domestic Product (GDP) 1992-01-01  7.138788e+09
209  Iceland   Gross Domestic Product (GDP) 1997-01-01  7.596126e+09
210  Iceland   Gross Domestic Product (GDP) 2002-01-01  9.161798e+09
211  Iceland   Gross Domestic Product (GDP) 2007-01-01  2.129384e+10
212  Iceland   Gross Domestic Product (GDP) 2012-01-01  1.419452e+10
213  Iceland   Gross Domestic Product (GDP) 2015-01-01  1.659849e+10
214  Iceland  National Rainfall Index (NRI) 1967-01-01  8.160000e+02
215  Iceland  National Rainfall Index (NRI) 1971-01-01  9.632000e+02
216  Iceland  National Rainfall Index (NRI) 1975-01-01  1.010000e+03
217  Iceland  National Rainfall Index (NRI) 1981-01-01  9.326000e+02
218  Iceland  National Rainfall Index (NRI) 1986-01-01  9.685000e+02
219  Iceland  National Rainfall Index (NRI) 1991-01-01  1.095000e+03
220  Iceland  National Rainfall Index (NRI) 1997-01-01  9.932000e+02
221  Iceland  National Rainfall Index (NRI) 1998-01-01  9.234000e+02

#### 7b) Print the years when the National Rainfall Index (NRI) was greater than 900 and less than 950 in Iceland. Use the dataframe you created in the previous question 'dftemp'. 

In [33]:
# your code here
dftemp = dftemp[:][dftemp['Variable Name'] == 'National Rainfall Index (NRI)']
dftemp = dftemp[:][dftemp['Value'] > 900]
dftemp = dftemp[:][dftemp['Value'] < 950]
dftemp

Area                  Variable Name       Year  Value
217  Iceland  National Rainfall Index (NRI) 1981-01-01  932.6
221  Iceland  National Rainfall Index (NRI) 1998-01-01  923.4

In [34]:
print("years when the National Rainfall Index (NRI) was greater than 900 and less than 950 in Iceland are:")
dftemp['Year']

years when the National Rainfall Index (NRI) was greater than 900 and less than 950 in Iceland are:


217   1981-01-01
221   1998-01-01
Name: Year, dtype: datetime64[ns]

## US statistics: 


#### 8a) Create a new DataFrame called **`df_usa`** that only contains values where 'Area' is equal to 'United States of America'. Set the indices to be the 'Year' column    ( Use .set_index( ) ). Display the dataframe head.

In [35]:
# your code here
df_usa = df1[:][df1['Area'] == 'United States of America']
df_usa = df_usa.set_index('Year')
df_usa

Area                  Variable Name  \
Year                                                                  
1962-01-01  United States of America      Total area of the country   
1967-01-01  United States of America      Total area of the country   
1972-01-01  United States of America      Total area of the country   
1977-01-01  United States of America      Total area of the country   
1982-01-01  United States of America      Total area of the country   
1987-01-01  United States of America      Total area of the country   
1992-01-01  United States of America      Total area of the country   
1997-01-01  United States of America      Total area of the country   
2002-01-01  United States of America      Total area of the country   
2007-01-01  United States of America      Total area of the country   
2012-01-01  United States of America      Total area of the country   
2014-01-01  United States of America      Total area of the country   
1962-01-01  United States of America               Total population   
1967-01-01  United States of America               Total population   
1972-01-01  United States of America               Total population   
1977-01-01  United States of America               Total population   
1982-01-01  United States of America               Total population   
1987-01-01  United States of America               Total population   
1992-01-01  United States of America               Total population   
1997-01-01  United States of America               Total population   
2002-01-01  United States of America               Total population   
2007-01-01  United States of America               Total population   
2012-01-01  United States of America               Total population   
2015-01-01  United States of America               Total population   
1962-01-01  United States of America             Population density   
1967-01-01  United States of America             Population density   
1972-01-01  United States of America             Population density   
1977-01-01  United States of America             Population density   
1982-01-01  United States of America             Population density   
1987-01-01  United States of America             Population density   
1992-01-01  United States of America             Population density   
1997-01-01  United States of America             Population density   
2002-01-01  United States of America             Population density   
2007-01-01  United States of America             Population density   
2012-01-01  United States of America             Population density   
2015-01-01  United States of America             Population density   
1962-01-01  United States of America   Gross Domestic Product (GDP)   
1967-01-01  United States of America   Gross Domestic Product (GDP)   
1972-01-01  United States of America   Gross Domestic Product (GDP)   
1977-01-01  United States of America   Gross Domestic Product (GDP)   
1982-01-01  United States of America   Gross Domestic Product (GDP)   
1987-01-01  United States of America   Gross Domestic Product (GDP)   
1992-01-01  United States of America   Gross Domestic Product (GDP)   
1997-01-01  United States of America   Gross Domestic Product (GDP)   
2002-01-01  United States of America   Gross Domestic Product (GDP)   
2007-01-01  United States of America   Gross Domestic Product (GDP)   
2012-01-01  United States of America   Gross Domestic Product (GDP)   
2015-01-01  United States of America   Gross Domestic Product (GDP)   
1965-01-01  United States of America  National Rainfall Index (NRI)   
1969-01-01  United States of America  National Rainfall Index (NRI)   
1974-01-01  United States of America  National Rainfall Index (NRI)   
1981-01-01  United States of America  National Rainfall Index (NRI)   
1984-01-01  United States of America  National Rainfall Index (NRI)   
1992-01-01  United States of America  National Rainfall Index (NRI)   
1996-01-01  United States of America  National Rainfall 


#### 8b) Pivot the DataFrame so that the unique values in the column 'Variable Name' becomes the columns. The DataFrame values should be the ones in the the 'Value' column. Save it in df_usa. Display the dataframe head.

In [36]:
# your code here
df_usa = pd.pivot_table(df_usa, values = 'Value' , columns = ['Variable Name'] , index = 'Year')
df_usa

Variable Name  Gross Domestic Product (GDP)  National Rainfall Index (NRI)  \
Year                                                                         
1962-01-01                     6.050000e+11                            NaN   
1965-01-01                              NaN                          928.5   
1967-01-01                     8.620000e+11                            NaN   
1969-01-01                              NaN                          952.2   
1972-01-01                     1.280000e+12                            NaN   
1974-01-01                              NaN                         1008.0   
1977-01-01                     2.090000e+12                            NaN   
1981-01-01                              NaN                          949.2   
1982-01-01                     3.340000e+12                            NaN   
1984-01-01                              NaN                          974.6   
1987-01-01                     4.870000e+12                            NaN   
1992-01-01                     6.540000e+12                         1020.0   
1996-01-01                              NaN                         1005.0   
1997-01-01                     8.610000e+12                            NaN   
2002-01-01                     1.100000e+13                          938.7   
2007-01-01                     1.450000e+13                            NaN   
2012-01-01                     1.620000e+13                            NaN   
2014-01-01                              NaN                            NaN   
2015-01-01                     1.790000e+13                            NaN   

Variable Name  Population density  Total area of the country  Total population  
Year                                                                            
1962-01-01                  19.93                   962909.0          191861.0  
1965-01-01                    NaN                        NaN               NaN  
1967-01-01                  21.16                   962909.0          203713.0  
1969-01-01                    NaN                        NaN               NaN  
1972-01-01                  22.14                   962909.0          213220.0  
1974-01-01                    NaN                        NaN               NaN  
1977-01-01                  23.17                   962909.0          223091.0  
1981-01-01                    NaN                        NaN               NaN  
1982-01-01                  24.30                   962909.0          233954.0  
1984-01-01                    NaN                        NaN               NaN  
1987-01-01                  25.49                   962909.0          245425.0  
1992-01-01                  26.78                   962909.0          257908.0  
1996-01-01                    NaN                        NaN               NaN  
1997-01-01                  28.34                   962909.0          272883.0  
2002-01-01                  29.95                   963203.0          288471.0  
2007-01-01                  31.32                   963203.0          301656.0  
2012-01-01                  32.02                   983151.0          314799.0  
2014-01-01                    NaN                   983151.0               NaN  
2015-01-01                  32.73                        NaN          321774.0

#### 8c) Rename new columns to  ['GDP','NRI','PD','Area','Population'] and display the head.



In [37]:
# your code her
df_usa.columns = [ 'GDP' ,'NRI','PD','Area','Population']

df_usa

GDP     NRI     PD      Area  Population
Year                                                         
1962-01-01  6.050000e+11     NaN  19.93  962909.0    191861.0
1965-01-01           NaN   928.5    NaN       NaN         NaN
1967-01-01  8.620000e+11     NaN  21.16  962909.0    203713.0
1969-01-01           NaN   952.2    NaN       NaN         NaN
1972-01-01  1.280000e+12     NaN  22.14  962909.0    213220.0
1974-01-01           NaN  1008.0    NaN       NaN         NaN
1977-01-01  2.090000e+12     NaN  23.17  962909.0    223091.0
1981-01-01           NaN   949.2    NaN       NaN         NaN
1982-01-01  3.340000e+12     NaN  24.30  962909.0    233954.0
1984-01-01           NaN   974.6    NaN       NaN         NaN
1987-01-01  4.870000e+12     NaN  25.49  962909.0    245425.0
1992-01-01  6.540000e+12  1020.0  26.78  962909.0    257908.0
1996-01-01           NaN  1005.0    NaN       NaN         NaN
1997-01-01  8.610000e+12     NaN  28.34  962909.0    272883.0
2002-01-01  1.100000e+13   938.7  29.95  963203.0    288471.0
2007-01-01  1.450000e+13     NaN  31.32  963203.0    301656.0
2012-01-01  1.620000e+13     NaN  32.02  983151.0    314799.0
2014-01-01           NaN     NaN    NaN  983151.0         NaN
2015-01-01  1.790000e+13     NaN  32.73       NaN    321774.0

#### 8d) Replace all 'Nan' values in df_usa with 0. Display the head of the dataframe.

In [38]:
# your code here
df_usa= df_usa.fillna(0)
df_usa

GDP     NRI     PD      Area  Population
Year                                                         
1962-01-01  6.050000e+11     0.0  19.93  962909.0    191861.0
1965-01-01  0.000000e+00   928.5   0.00       0.0         0.0
1967-01-01  8.620000e+11     0.0  21.16  962909.0    203713.0
1969-01-01  0.000000e+00   952.2   0.00       0.0         0.0
1972-01-01  1.280000e+12     0.0  22.14  962909.0    213220.0
1974-01-01  0.000000e+00  1008.0   0.00       0.0         0.0
1977-01-01  2.090000e+12     0.0  23.17  962909.0    223091.0
1981-01-01  0.000000e+00   949.2   0.00       0.0         0.0
1982-01-01  3.340000e+12     0.0  24.30  962909.0    233954.0
1984-01-01  0.000000e+00   974.6   0.00       0.0         0.0
1987-01-01  4.870000e+12     0.0  25.49  962909.0    245425.0
1992-01-01  6.540000e+12  1020.0  26.78  962909.0    257908.0
1996-01-01  0.000000e+00  1005.0   0.00       0.0         0.0
1997-01-01  8.610000e+12     0.0  28.34  962909.0    272883.0
2002-01-01  1.100000e+13   938.7  29.95  963203.0    288471.0
2007-01-01  1.450000e+13     0.0  31.32  963203.0    301656.0
2012-01-01  1.620000e+13     0.0  32.02  983151.0    314799.0
2014-01-01  0.000000e+00     0.0   0.00  983151.0         0.0
2015-01-01  1.790000e+13     0.0  32.73       0.0    321774.0

## Note: Use df_usa

#### 9a) Multiply the 'Area' column for all countries by 10 (so instead of 1000 ha, the unit becomes 100 ha = 1km^2). Display the dataframe head.


In [39]:
# your code here
df_usa['Area'] = df_usa['Area']*10
df_usa

GDP     NRI     PD       Area  Population
Year                                                          
1962-01-01  6.050000e+11     0.0  19.93  9629090.0    191861.0
1965-01-01  0.000000e+00   928.5   0.00        0.0         0.0
1967-01-01  8.620000e+11     0.0  21.16  9629090.0    203713.0
1969-01-01  0.000000e+00   952.2   0.00        0.0         0.0
1972-01-01  1.280000e+12     0.0  22.14  9629090.0    213220.0
1974-01-01  0.000000e+00  1008.0   0.00        0.0         0.0
1977-01-01  2.090000e+12     0.0  23.17  9629090.0    223091.0
1981-01-01  0.000000e+00   949.2   0.00        0.0         0.0
1982-01-01  3.340000e+12     0.0  24.30  9629090.0    233954.0
1984-01-01  0.000000e+00   974.6   0.00        0.0         0.0
1987-01-01  4.870000e+12     0.0  25.49  9629090.0    245425.0
1992-01-01  6.540000e+12  1020.0  26.78  9629090.0    257908.0
1996-01-01  0.000000e+00  1005.0   0.00        0.0         0.0
1997-01-01  8.610000e+12     0.0  28.34  9629090.0    272883.0
2002-01-01  1.100000e+13   938.7  29.95  9632030.0    288471.0
2007-01-01  1.450000e+13     0.0  31.32  9632030.0    301656.0
2012-01-01  1.620000e+13     0.0  32.02  9831510.0    314799.0
2014-01-01  0.000000e+00     0.0   0.00  9831510.0         0.0
2015-01-01  1.790000e+13     0.0  32.73        0.0    321774.0


#### 9b) Create a new column in df_usa called 'GDP/capita' and populate it with the calculated GDP per capita. Round the results to two decimal points. Display the dataframe head.
GDP per capita = (GDP / Population)

In [40]:
# your code here
df_usa['GDP/capita'] = df_usa['GDP']/df_usa['Population']
df_usa.head()

GDP    NRI     PD       Area  Population    GDP/capita
Year                                                                       
1962-01-01  6.050000e+11    0.0  19.93  9629090.0    191861.0  3.153325e+06
1965-01-01  0.000000e+00  928.5   0.00        0.0         0.0           NaN
1967-01-01  8.620000e+11    0.0  21.16  9629090.0    203713.0  4.231443e+06
1969-01-01  0.000000e+00  952.2   0.00        0.0         0.0           NaN
1972-01-01  1.280000e+12    0.0  22.14  9629090.0    213220.0  6.003189e+06


#### 9c) Find the maximum value of the 'NRI' column in the US (using pandas methods). What year does the max value occur? Display the values.

In [41]:
# your code here
NRI_max= df_usa['NRI'].max()
df_NRI_max = df_usa[:][df_usa['NRI'] == NRI_max]
print("The max Value of NRI occurs in the year" , df_NRI_max.index.format(formatter=lambda t: f'{t:%Y}') , "and the max NRI is ", NRI_max )


The max Value of NRI occurs in the year ['1992'] and the max NRI is  1020.0
